baseurl                 = "https://alexchiri.com/"
DefaultContentLanguage  = "en"
title                   = "alexchiri.com"
theme                   = "hugo-future-imperfect-slim"
preserveTaxonomyNames   = true
paginate                = 5
disqusShortname         = "alexchiricom"
googleAnalytics         = "UA-37431001-1"
pluralizeListTitles     = false
disableLanguages        = [""]

[params]
  mainSections = ["post"]
  # Loads CSS and JavaScript files. The variable is an array so that you can load
  # multiple/additional files if necessary. The standard theme files can be loaded
  # by adding the value, "default". Default includes the add-on.css and and-on.js.
  # Example: ["default", "/path/to/file"]
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  # Sets options for highlight.js
  highlightjs           = true
  highlightjsTheme      = "github"
  highlightjsLang       = ["html", "css", "js", "toml"]
  # Sets where "View More Posts" links to
  viewMorePostsLink     = "/blog/"
  # Activate Estimated Reading Times, which appear in the post headers
  readingTime           = true
  # Sets which Social Share links appear in posts.
  # Options are twitter, facebook, reddit, linkedin, pinterest, email
  socialShare           = []

  [params.meta]
    # Sets the meta tag description
    description         = "Random thoughts on work, people and improvements."
    # Sets the meta tag author
    author              = "Alex Chiritescu"
    # If you would like to add more comprehensive favicon support passed root
    # directory favicon.ico, utlize this funtion. It is recommened to use
    # https://realfavicongenerator.net to generate your icons as that is the basis
    # for the theme's naming.
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff" # Copy from the https://realfavicongenerator.net
    iOSColor            = "#ffffff" # Copy from the https://realfavicongenerator.net

  [params.header]
    # Sets the navbarTitle that appears in the top left of the navigation bar
    navbarTitle         = "alexchiri.com"
    # Sets navbarTitle to match the section of the website
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = false
    languageMenu        = false

  # These are optional params related to the sidebar. They are recommended, but not
  # required for proper functionality. HTML is supported within the params.
  [params.intro]
    header                = "Alex Chirițescu"
    paragraph             = "My #purpose is to help create #safe work #environments that enable #people to be #happy, #creative, #effective and #proud of their work."
    rssIntro              = true
    socialIntro           = true

    # This appears at the top of the sidebar above params.intro.header.
    # A width of less than 100px is recommended from a design perspective.
    [params.intro.pic]
      src                 = "/img/main/logo.png"
      # Masks image in a certain shape. Supported are circle, triangle, diamond, and hexagon.
      shape               = "circle"
      width               = "100"
      alt                 = "Alex Chiritescu"

  [params.sidebar]
    # about               = "test"
    # Sets the number of recent posts to show in the sidebar. The default value is 5.
    postAmount          = 5
    # set to show or to hide categories in the sidebar
    categories          = true
    # Sets Categories to sort by number of posts instead of alphabetical
    categoriesByCount   = true

  [params.footer]
    # Sets RSS icons to appear on the sidebar with the social media buttons
    rssFooter           = true
    # Sets Social Media icons to appear on the sidebar
    socialFooter        = true

[menu]
  # Sets the menu items in the navigation bar
  # Identifier prepends a Font Awesome icon to the menu item
  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "Now"
    identifier        = "now"
    url               = "/now/"
    pre               = "<i class='fas fa-id-card'></i>"
    weight            = 2

  # [[menu.main]]
  #   name              = "Reading Notes"
  #   identifier        = "reading-notes"
  #   url               = "/reading-notes/"
  #   pre               = "<i class='fas fa-book'></i>"
  #   weight            = 3

# Sets Social Media icons to appear and link to your account. Value should be your
# username unless otherwise noted. These are the icons affected by socialAppearAtTop
# and socialAppearAtBottom.
[social]
  # Coding Communities
  github           = "alexchiri"
  stackoverflow    = "1904089" # User Number
  linkedin         = "alexchiri"
  twitter          = "alexchiri"
  email            = "alex.chiri@gmail.com"